base_url = "https://vsfl.org"

compile_sass       = false
minify_html        = true
generate_feeds     = true
generate_sitemap   = true
build_search_index = true

theme = "linkita"

default_language = "en"
author           = "Ivan Schaller"

title       = "vier steht für lifestyle"
description = "Personal site of Ivan Schaller"
taxonomies  = [{ name = "tags" }]

[languages.de]
title              = "vier steht für lifestyle"
description        = "Persönliche website von Ivan Schaller"
taxonomies         = [{ name = "tags" }]
build_search_index = true

[markdown]
highlight_code              = true
render_emoji                = true
external_links_target_blank = true
smart_punctuation           = true
highlight_theme             = "gruvbox-dark"

[slugify]
paths      = "on"
taxonomies = "on"
anchors    = "on"

[extra]
toc                       = true
page_summary_on_paginator = true
math                      = true
mermaid                   = true
disable_default_favicon   = true

header_menu_name = "multilingual_menu"
header_buttons = [
    "site_title",
    "theme_button",
    "translations_button",
    "search_button",
]

# Valid "when" values:
#  "date", "date_updated", "reading_time", "word_count", "authors", "tags", "".
# The "prepend" and "append" are used when the value of "when" is defined for the page.
# e.g. [{when="", prepend="Page Info: "},{when="date",prepend="Published on "},{when="authors",prepend="By "}]
page_info = [
    { when = "date" },
    { when = "date_updated", prepend = "(updated: ", append = ")" },
    { when = "reading_time" },
    { when = "word_count" },
    { when = "authors" },
]
page_info_on_paginator = [
    { when = "date" },
    { when = "date_updated", prepend = "(updated: ", append = ")" },
    { when = "reading_time" },
    { when = "word_count" },
]

[extra.menus]
multilingual_menu = [
    { url = "$BASE_URL/about/", names = { en = "About me", de = "Über mich" } },
    { url = "/projects/", names = { en = "Projects", de = "Projekte" } },
    { url = "/blog/", names = { en = "Blog", de = "Blog" } },
]

[extra.profiles.olofvndrhr]
name = "Ivan Schaller"
bio  = "Network Engineer"

avatar_url = "media/avatar.png"
social = [
    { name = "github", url = "https://github.com/olofvndrhr" },
]

[extra.profiles.olofvndrhr.languages.de]
bio = "Network Engineer"

[extra.footer]
since       = 2025
license_url = "https://creativecommons.org/licenses/by-sa/4.0/deed"
copyright   = "&copy; $YEAR Ivan Schaller &vert; [CC BY-SA 4.0]($LICENSE_URL)"
