base_url = "https://vsfl.org"

compile_sass     = true
minify_html      = true
default_language = "en"

generate_feeds   = true
generate_sitemap = true

theme = "anemone"

[languages.en]
build_search_index = true
title              = "Personal site"
description        = "Personal site of Ivan Schaller"

[markdown]
highlight_code              = true
render_emoji                = true
external_links_target_blank = true
smart_punctuation           = true
highlight_theme             = "gruvbox-dark"

[slugify]
paths      = "on"
taxonomies = "on"
anchors    = "on"

[link_checker]
internal_level = "warn"

[extra]
list_pages    = false
enable_search = true

header_nav = [
    { url = "/", name_en = "/home/" },
    { url = "/about", name_en = "/about/" },
    { url = "/projects", name_en = "/projects/" },
]
